# Controller Gains [x,y,z, Rx,Ry,Rz]
# kp: [0.15,0.15,0.1, 0.15,0.15,0.15]
# kp: [0.15,0.15,0.1, 0.15,0.15,0.15]
# kp: [0.1,0.1,0.075, 0.15,0.15,0.15]
kp: [0.05,0.05,0.025, 0.15,0.15,0.15]
# kp: [0.03,0.03,0.03, 0.05,0.05,0.05]
# kp: [0.02,0.02,0.02, 0.1,0.1,0.1]
# kp: [0.06,0.06,0.03, 0.03,0.03,0.03]
kd: [0.0,0.0,0.0, 0.0,0.0,0.0]

# Particle/Segment ids of the tip points of the tent pole 
# to be placed into the grommets
tip_particles: [0,39]

# Grommet poses as targets for the tip points
# Each element holds [[x,y,z],[Rx,Ry,Rz(euler angles in degrees)]]
target_poses: [[[-1, -1, 0.14], [5,   0, 90]],
               [[ 1, -1, 0.14], [175, 0, 90]]]

obstacle_avoidance_enabled: True # default:True 

# offset distance from the obstacles
d_obstacle_offset: 0.05 # (meter) 

# 

